baseURL: https://eversewslowly.com/
rssLimit: 15
languageCode: en-us
title: Ever Sew Slowly
theme: navada
paginate: 6
googleAnalytics: ''
pygmentsstyle: Abyss
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
enableEmoji: true
params:
  title: Ever Sew Slowly
  tagline: Sharing my pin pricks in the hopes you may be spared
  author: Ever Sew Slowly (Rose)
  authorImage: /images/eversewslowly_logo.jpg
  description: Website to organize all of my sewing refashioning endeavours
  NewsletterSignup: https://tinyletter.com/eversewslowly
  favicon: /images/2023/refashion_mens_shirt.png
  logo: 
  rss: true
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  footer:
    - name: About
      url: /about
    - name: Home
      url: /
  main:
    - name: About
      url: /about
    - name: Blog
      url: /blog
    - name: Categories
      url: /categories
    - name: Tags
      url: /tags
    - name: Subscribe
      url: /subscribe
  social:
    - name: Instagram
      pre: <i class="fab fa-instagram fa-1x"></i>
      url: https://instagram.com/eversewslowly/
    - name: Pinterst
      pre: <i class='fab fa-pinterest-p fa-1x'></i>
      url: https://pinterest.com/EverSewSlowly/
    - name: Youtube
      pre: <i class='fab fa-youtube fa-1x'></i>
      url: https://youtube.com/@eversewslowly/
related:
  includeNewer: yes
  indices:
    - name: categories
      weight: 100
    - name: date
      weight: 10
  threshold: 0
  toLower: no
module:
  hugoVersion:
    extended: yes
    max: 0.110.0
    min: 0.55.0
